#!/usr/bin/perl -w

# Description
# ===========
#  This utility is designed to play with variables in perl
#  We have learnt that Perl has the following three basic data types −
#
#    Scalars
#    Arrays
#    Hashes
#  

use strict;

# example of a Scalar not an Array not a Map a single data unit.
my $age = 25;
print "$age\n";

# example of an array
my @ages = (25, 30, 40);             
my @names = ("John Paul", "Lisa", "Eugene");

print "@ages\n";
print "@names\n";
print "\$ages[0]=$ages[0]\n";
print "\$ages[1]=$ages[1]\n";

# example of Hash Variables like a dicitonary or a Hash Table
my %data = ('John Paul', 45, 'Lisa', 30, 'Kumar', 40);
print "\$data{'John Paul'}= $data{'John Paul'}\n";

# it is a scalar in an array of 1 so first value of the assigned array gets assigned to $ascalar
my ($ascalar) = (25,30);
print "$ascalar\n";

# below are 2 scalars in an array assigned to the relevant indexes of assigned array
my ($var1 , $var2) = ("hadi",19);
# an array can have an integer and string scalar at last they are all scalars
# and can be used interchangeably
print "\$var1=$var1\n";
print "\$var2=$var2\n";
